---
# Adding elastic key
- apt_key:
    url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    state: present

# Adding elastic repo
- apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/{{ logstash_version }}.x/apt stable main"
    state: present
    filename: 'elastic-{{ logstash_version }}.x'

# Installing logstash
- name: Install Logstash.
  apt: 
    name: logstash 
    state: present
    update_cache: yes
  notify:
   - restart logstash
