---
- name: Update the apt package list (ubuntu)
  apt:
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: dependencies are installing. (ubuntu)
  apt:
    name: "{{ dependency }}"
    state: present
  when: ansible_os_family == 'Debian'

- name: Update the yum cache (Red Hat)
  yum:
    update_cache: yes
  when: ansible_os_family == 'RedHat'    

- name: dependencies are installed (Red Hat)
  yum:
    name: "{{ dependency }}"
    state: present
  when: ansible_os_family == 'RedHat'
      
